// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movie_Db.Data;

namespace Movie_Db.Migrations
{
    [DbContext(typeof(Movie_DbContext))]
    partial class Movie_DbCotextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Movie_DbModels.Movie", b =>
            {
                b.Property<Guid>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("Genre")
                    .HasColumnType("nvarchar(max");

                b.Property<string>("MovieName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Movielength")
                    .HasColumnType("int");

                b.HasKey("ID");

                b.ToTable("Movie");

                b.HasData(
                    new
                    {
                        ID = new Guid("c9f777a1-6166-471a-87db-2ef29ed1cd5a"),
                        DateOfBirth = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Movie"
                    });
            });
#pragma warning restore 612, 618
        }
    }
}
